-- Format for overwriting define values:
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 400
NDefines.NDiplomacy.CHARTER_COMPANY_BASE_COST = 2000
NDefines.NDiplomacy.CHARTER_COMPANY_MINIMUM_COST = 200
NDefines.NCountry.MAXIMUM_CONDOTTIERI = 40
NDefines.NCountry.RANDOM_LUCKY_TECH_WEIGHT = 0
NDefines.NCountry.RANDOM_LUCKY_SLOW_TECH_PENALTY = 0
NDefines.NCountry.RANDOM_LUCKY_DEVELOPMENT_WEIGHT = 0
NDefines.NCountry.MERCHANT_REPUBLIC_SIZE_LIMIT = 25
NDefines.NCountry.CORE_LOSE_CULTURE_GROUP = 200
NDefines.NCountry.CORE_LOSE_PRESTIGE = -5.0
NDefines.NCountry.MONARCH_MIN_SKILL = 2
NDefines.NCountry.MIN_DEV_FOR_FREE_CITY = 8
NDefines.NDiplomacy.MAX_FREE_CITIES = 16